site_name: "PCDC Aggregated Data Dictionary"
markdown_extensions:
  - attr_list
docs_dir: linkml_data_dictionary/markdown_model_generated
site_dir: docs
nav:
  - Index: index.md
theme:
  name: material
  favicon: img/favicon.ico
  font:
    text: Raleway
  features:
    - navigation.instant
    - toc.integrate
    - navigation.top
extra_css:
  - stylesheets/extra.css